### ISSUE TITLE
i cant use the mod in the steme bater it looks cool 

### ISSUE THREAD

**Issue by furigayming** [andro951/WeaponEnchantments#1]
![20220611004150_1](https://user-images.githubusercontent.com/107284255/173163199-b7ccae04-5a86-40ac-96cc-c70694049ac6.jpg)

**Comment by andro951** [comment]
It's possible you were on a different version such as preview.  If you are still having issues, please let me know:
[https://discord.gg/hEKKVsFBMd](https://steamcommunity.com/linkfilter/?url=https://discord.gg/hEKKVsFBMd)
