### ISSUE TITLE
PLEASE PLEASE PLEASEEEEEEEEEEE do this

### ISSUE THREAD

**Issue by 0rangeEcHO** [andro951/WeaponEnchantments#13]
nvm

**Comment by ShatteredEcHOs** [comment]
lmao i didnt read the "read me" I'm stupid lmao k nvm ty

**Comment by Kiroto** [comment]
Next time, instead of editing an issue, leave it there, without editing it into a "nvm". It allows for clarity for new features and why it wasn't implemented at the time.

**Comment by 0rangeEcHO** [comment]
Will do
