### ISSUE TITLE
Bug: Reforging while enchantments are in the weapon

### ISSUE THREAD

**Issue by Im-Beast** [andro951/WeaponEnchantments#2]
#### Description
When enchants are inserted into a weapon and then someone tries to reforge it, enchantments disappear and infusion power gets set to the negative max value of int32.

#### Possible fixes
You could either warn player before reforging to remove enchantments from the weapon or somehow fix it.

**Comment by andro951** [comment]
This was a bug due to changes I had to make when calamity came out.  It has since been fixed.
