### ISSUE TITLE
Leveling system

### ISSUE THREAD

**Issue by teoxihuitl** [andro951/WeaponEnchantments#3]
I just have a question on the leveling system. Is it supposed to do anything or just for looks bc i see that it says points available but i dont know where to use them

**Comment by andro951** [comment]
The levels are for applying enchantments.  Each enchantment has a cost that is how many level points it requires to apply.  If you have more questions, take a look at the Wiki.txt in this repository or jump on discord and we'll help out. [https://discord.gg/hEKKVsFBMd](https://steamcommunity.com/linkfilter/?url=https://discord.gg/hEKKVsFBMd)
