### ISSUE TITLE
AnarchulesBeetleBossBag from Vitality Mod

### ISSUE THREAD

**Issue by Gazzoo-byte** [andro951/WeaponEnchantments#4]
Hello! I got a notification advising to inform you that the Anarchules Beetle Boss Bag has not been implemented, I'm not sure what other information may be useful so I'll link a few tidbits I think might be helpful

https://terrariamods.fandom.com/wiki/Vitality_Mod/Anarchules_Beetle

https://steamcommunity.com/workshop/filedetails/?id=2568847048

**Comment by andro951** [comment]
That is all I need thank you.  I'll try to get it added into the next update.

**Comment by andro951** [comment]
Support added in the new update
