### ISSUE TITLE
Bug? - Hammers don't get experience via walls

### ISSUE THREAD

**Issue by Mrbt0907** [andro951/WeaponEnchantments#6]
I am unsure if this is intended or not, but you cannot get experience from destroying walls with hammers.

This forced me to use Essence Orbs to level hammers up.

**Comment by andro951** [comment]
I think this should work now, but it will be extremely slow to level them by using them.

**Comment by andro951** [comment]
The previous attempt did now work.  It does work now on my test build and will be released in the next update.
