### ISSUE TITLE
"Prevented an issue that would cause you to loose experience..."

### ISSUE THREAD

**Issue by ghost** [andro951/WeaponEnchantments#8]
![20220805181947_1](https://user-images.githubusercontent.com/94040719/183058240-2d557f81-ebea-4531-9612-3201106f247c.jpg)

Right after I defeated Skeletron I equipped the Bone Glove then shot a demon eye with my Revolver, then this appeared on the chat box.

**Comment by andro951** [comment]
This issue has been fixed, thanks for the report =D
